export const NAMES_DATA_REQUEST = "NAMES_DATA_REQUEST"
export const NAMES_DATA_SUCCESS = "NAMES_DATA_SUCCESS"
export const NAMES_DATA_FAILURE = "NAMES_DATA_FAILURE"

export const DETAILS_DATA_REQUEST = "DETAILS_DATA_REQUEST"
export const DETAILS_DATA_SUCCESS = "DETAILS_DATA_SUCCESS"
export const DETAILS_DATA_FAILURE = "DETAILS_DATA_FAILURE"